spring:
  datasource:
    url: jdbc:${DB_SGDB}://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  jpa:
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger

# prop custom pour l'implementation de JWT
app:
  security:
    jwt:
      access-expires-at: ${JWT_ACCESS_DURATION} # 15 min
      refresh-expires-at: ${JWT_REFRESH_DURATION} # 30 j
      prefix: ${JWT_PREFIX}
      auth-header: ${JWT_HEADER}
      access-secret: ${JWT_SECRET}
      refresh-secret: ${JWT_REFRESH_SECRET}
