spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/digital_airport_db
    username: postgres
    password: Test1234=
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger

logging:
  level:
    org:
      springframework:
        jdbc:
          datasource:
            init: debug

# prop custom pour l'implementation de JWT
app:
  security:
    jwt:
      access-expires-at: 900_000 # 15 min
      refresh-expires-at: 2_592_000_000 # 30 j
      prefix: "Bearer "
      auth-header: "Authorization"
      access-secret: ${JWT_SECRET}
      refresh-secret: ${JWT_REFRESH_SECRET}
